- name: private ec2
  become: true
  hosts: private
  tasks:

    - name: Install Apache
      apt: 
        name: apache2
        update_cache: yes

    - name: change web file
      shell: echo "<h1>Hello ansible from $(hostname -f)</h1>" > /var/www/html/index.html